---
- hosts: localhost
  connection: local
  gather_facts: false
#  vars_files:
#  - vars/common.yml
#  - vars/k8s.yml
  roles:
  - role: common
    vars:
      env: env1
    tags:
    - common

  - role: common
    vars:
      env: env2
    tags:
    - common