---
- hosts: localhost
  connection: local
  become_user: root
#  become: true
  become_method: sudo
  gather_facts: false
#  vars_files:
#  - vars/common.yml
#  - vars/k8s.yml
  roles:
  - role: common
    tags:
    - common
