- name: Deploy Azure App Service Environment
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
  - name: Create a resource group
    azure_rm_resourcegroup:
      name: azure-ase3-cdelapaz
      location: eastus
      tags:
        testing: testing
        delete: never

  - name: Create a Virtual Network (VNET)
    azure_rm_virtualnetwork:
      resource_group: azure-ase3-cdelapaz
      name: azure-ase3-vnet
      address_prefixes: "10.0.0.0/16"

  - name: Add a subnet in the VNET
    azure_rm_subnet:
      resource_group: azure-ase3-cdelapaz
      name: azure-ase3-subnet
      address_prefix: "10.0.1.0/24"
      virtual_network: azure-ase3-vnet
    register: subnet_out
  - debug:
      var: subnet_out.state.id

  - name: "Create Azure App Service Env"
    azure.azcollection.azure_rm_resource:
      idempotency: yes
      api_version: '2022-03-01'
      polling_timeout: 600
      polling_interval: 30
      resource_group: azure-ase3-cdelapaz
      provider: Web
      resource_type: hostingEnvironments
      resource_name: azure-ase3-test
      body: {
        "kind": "ASEv3",
        "location": "eastus",
        "properties": {
          "virtualNetwork": {
            "id": "/subscriptions/aaaaa147-fd6e-48fb-9a66-d044700dca17/resourceGroups/azure-ase3-cdelapaz/providers/Microsoft.Network/virtualNetworks/azure-ase3-vnet/subnets/azure-ase3-subnet"
          }
        }
      }
  #     resource_group: "azure-ase3-cdelapaz"
  #     provider: "Web"
  #     resource_type: "hostingEnvironments"
  #     resource_name: "azure-ase3-test"
  #     api_version: "2022-03-01"
  #     body:
  #       location: "eastus"
  #       kind: "ASEV3"
  #       properties:
  #         # internalLoadBalancingMode: "None"
  #         virtualNetwork:
  #           id: "{{ subnet_out.state.id }}"
  #           subnet: "azure-ase3-subnet"
  #         # networkingConfiguration: {}
  #         # customDnsSuffixConfiguration: ".p.azurewebsites.net"
  #         # dedicatedHostCount: 1
  #       # identity:
  #       #   type: SystemAssigned
  #   register: "ase3out"
  # - debug:
  #     var: "ase3out.stout"

  # - name: Create ASEv3
  #   azure.azcollection.azure_rm_resource:
  #     idempotency: yes
  #     api_version: '2022-03-01'
  #     polling_timeout: 600
  #     polling_interval: 30
  #     # url: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/virtualNetworks/{virtualNetworkName}/subnets/{subnetName}
  #     resource_group: rg-plow-dev
  #     provider: Web
  #     resource_type: hostingEnvironments
  #     resource_name: ase-plow-dev
  #     body: {
  #       "kind": "ASEv3",
  #       "location": "South Central US",
  #       "properties": {
  #         "virtualNetwork": {
  #           "id": "/subscriptions/87232d10-042d-4db2-b5c9-549ce082e065/resourceGroups/rg-core-infra/providers/Microsoft.Network/virtualNetworks/vnet-plow-001/subnets/snet-ase-232-0"
  #         }
  #       }
  #     }





  # - name: "Create Azure App Service Env 2019-04-01"
  #   azure.azcollection.azure_rm_resource:
  #     idempotency: true
  #     resource_group: "azure-ase3-cdelapaz"
  #     provider: "Web"
  #     resource_type: "hostingEnvironments"
  #     resource_name: "azure-ase3-test"
  #     api_version: "2019-08-01"
  #     body:
  #       # name: "azure-ase3-test"
  #       location: "eastus"
  #       kind: "ASEV3"
  #       properties:
  #         name: "azure-ase3-test"
  #         location: "eastus"
  #         internalLoadBalancingMode: "None"
  #         virtualNetwork:
  #           id: "/subscriptions/aaaaa147-fd6e-48fb-9a66-d044700dca17/resourceGroups/azure-ase3-cdelapaz/providers/Microsoft.Network/virtualNetworks/azure-ase3-vnet/subnets/azure-ase3-subnet"
  #           subnet: "azure-ase3-subnet"
  #         # networkingConfiguration: {}
  #         # customDnsSuffixConfiguration: ".p.azurewebsites.net"
  #         dedicatedHostCount: 1
  #         # zoneRedundant:  false
  #         # workerPools: []
  #       # identity:
  #       #   type: SystemAssigned
  #   register: "ase3out"
  # - debug:
  #     var: "ase3out.stout"

