- name: Create a VM on Azure cloud
  hosts: localhost
  connection: local

#  vars_prompt:
#    - name: admin_password
#      prompt: "Enter Local Admin Password"  

  tasks:

  - name: Create a Virtual Network (VNET)
    azure_rm_virtualnetwork:
      resource_group: ansible-awx-test
      name: myVnet-cdelapaz
      address_prefixes: "10.0.0.0/16"

  - name: Add a subnet in the VNET
    azure_rm_subnet:
      resource_group: ansible-awx-test
      name: mySubnet-cdelapaz
      address_prefix: "10.0.1.0/24"
      virtual_network: myVnet-cdelapaz

  - name: Create a public IP address
    azure_rm_publicipaddress:
      resource_group: ansible-awx-test
      allocation_method: Static
      name: myPublicIP-cdelapaz
    register: output_ip_address

#  - name: Print Public IP of VM
#    debug:
#      msg: "The public IP of VM is {{ output_ip_address.state.ip_address }}."

  - name: Create a Network Security Group (NSG) that allows SSH (port 22)
    azure_rm_securitygroup:
      resource_group: ansible-awx-test
      name: myNetworkSecurityGroup-cdelapaz
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound

  - name: Create a virtual Network Interface Card (NIC)
    azure_rm_networkinterface:
      resource_group: ansible-awx-test
      name: myNIC-cdelapaz
      virtual_network: myVnet-cdelapaz
      subnet: mySubnet-cdelapaz
      public_ip_name: myPublicIP-cdelapaz
      security_group: myNetworkSecurityGroup-cdelapaz

  - name: Create managed disk
    azure_rm_manageddisk:
      name: myDisk-cdelapaz
      location: eastus
      resource_group: ansible-awx-test
      storage_account_type: Standard_LRS 
#      disk_size_gb: 30
    register: myDisk
  - debug:
      var: myDisk.state.id

  - name: Create a VM
    azure_rm_virtualmachine:
      resource_group: ansible-awx-test
      name: myVM-cdelapaz
      vm_size: Standard_DS1_v2
      admin_username: ubuntu
      admin_password: MyStrongPassw0rd!
      network_interfaces: myNIC-cdelapaz
      image:
        offer: 0001-com-ubuntu-server-focal
        publisher: canonical
        sku: '20_04-lts-gen2'
        version: latest
      data_disks:
        - lun: 0
          managed_disk_id: "{{ myDisk.state.id }}"
