- name: Create a public IP address
  azure_rm_publicipaddress:
    name: abs-az-public-ip
    resource_group: abs-az-resource-group
    allocation_method: Static
  register: output_ip_address

- name: Print Public IP of VM
  debug:
    msg: "The public IP of VM is output_ip_address.state.ip_address."